### PR TITLE
Private AKS Cluster

### PR DESCRIPTION
**Pull request by vermacodes**
### Ability to create private AKS Clusters
- A new variable named 'private_cluster_enabled' has been added.
- It defaults to 'false' which then creates a public AKS Cluster.
- User has an option to set it to 'true' and a private AKS Cluster will be created instead.

#### Important Docs
https://docs.microsoft.com/en-us/azure/aks/private-clusters
https://registry.terraform.io/providers/hashicorp/azurerm/2.67.0/docs/resources/kubernetes_cluster#private_cluster_enabled

### CODE REVIEW

**Comment by vermacodes** [comment]
Tested and looks good.

**Comment by vermacodes** [comment]
Resolved #90

**Comment by fabiendelpierre** [comment]
Hi there,

Thanks for submitting this, I see no issue with it.

Just an FYI, we're a company and were using this module as the basis for a private TF module for internal use only. We've since stopped using this module and severed our internal module's dependency on it, resulting in this one no longer being maintained.

While you're free to use this module of course, I would steer you toward the community module as it's actively maintained and updated: https://github.com/Azure/terraform-azurerm-aks. The advantage of this module is that it's simpler to use, but probably doesn't do a lot of things that the other one does, and may stop working one day if something changes in the Terraform provider or the Azure API 😄 

Anyway, I'm going to merge this shortly. I don't have time to test it but it looks simple enough that it can't break anything, and you said you tested it, so I'll just trust that.

**Review by fabiendelpierre — APPROVED** [review]

**Comment by fabiendelpierre** [comment]
Released in [v4.3.0](https://github.com/Azure-Terraform/terraform-azurerm-kubernetes/releases/tag/v4.3.0).

**Pull request merged**
